name: 'Camunda 8 Action'
description: 'A GitHub action to interact with Camunda SaaS'
author: 'Josh Wulf'
branding:
  icon: 'upload-cloud'  
  color: 'orange'
inputs:
  operation: # change this
    required: true
    description: 'The operation to perform. One of publishMessage | createProcessInstance | createProcessInstanceWithResult | deployProcess | startWorker'
  messageName: 
    required: false
    description: "The name of the message for a publishMessage operation"
  variables: 
    required: false
    description: "The stringified JSON of the variables for the operation"
    default: "{}"
  correlationKey:
    required: false
    description: "The correlationKey for a publishMessage operation"
  timeToLive: 
    required: false
    description: "The timeToLive for the message sent by a publishMessage operation"
  bpmnFilename:
    required: false
    description: "The bpmn file to deploy"
  bpmnDirectory:
    required: false
    description: "A directory from which to deploy bpmn files"
  bpmnProcessId:
    required: false
    description: "The id of the process definition for a createProcessInstance operation"
  requestTimeout:
    required: false
    description: "The requestTimeout for a createProcessInstanceWithResult operation"
  zeebeAddress: 
    required: false
    description: "The ZEEBE_ADDRESS from your Camunda SaaS client credentials"
  zeebeClientId: 
    required: false
    description: "The ZEEBE_CLIENT_ID from your Camunda SaaS client credentials"
  zeebeClientSecret: 
    required: false
    description: "The ZEEBE_CLIENT_SECRET from your Camunda SaaS client credentials"
  zeebeAuthorizationServerUrl: 
    required: false
    description: "The ZEEBE_AUTHORIZATION_SERVER_URL from your Camunda SaaS client credentials"
  clientConfig:
    required: true
    description: "The client credentials for Camunda SaaS"
  workerHandlerFile: 
    required: false
    description: "The file in your repo to load the worker handlers from"
  workerLifetimeMins:
    required: false
    description: "The number of minutes that the workers stay active"
    default: "10"
  verbose: 
    required: false
    description: Set to true for verbose debugging information
  quiet:
    required: false
    description: Set the LOGLEVEL of the Zeebe Client and Worker to NONE
outputs:
  result: # id of the output
    description: 'The JSON stringified response from the operation, if a createProcess operation'

runs:
  using: 'node16'
  main: 'dist/index.js'
